## 향미방

### 1> 데이터 확인

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as spst

import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# raw_data = pd.read_excel('./data/raw_data/(Metabolite)GC-Volatile_250529.xlsx', sheet_name='RAW_DATA', index_col=0).T
# raw_data.head(2)

Compounds  Carbon disulfide  Methylsulfanylmethane (Dimethyl sulfide)   \
0_1                0.130670                                        0.0   
0_2                0.167196                                        0.0   

Compounds  2-Methylheptane  Furan  Propan-2-one  4-Methyloctane    \
0_1               0.000000    0.0      1.435842          0.517948   
0_2               0.027512    0.0      0.952583          0.000000   

Compounds  (E)-oct-2-ene  2-Methylfuran  Butan-2-one    Nonane  ...  \
0_1                  0.0            0.0       0.175037     0.0  ...   
0_2                  0.0            0.0       0.332735     0.0  ...   

Compounds  Undecan-4-ylbenzene (4-Phenylundecane)  Phenylmethanol  \
0_1                                           0.0             0.0   
0_2                                           0.0             0.0   

Compounds  (1-hydroxy-2,4,4-trimethylpentan-3-yl) 2-methylpropanoate    \
0_1                                                      0.0             
0_2                                                      0.0             

Compounds  Methylsulfonylmethane (Dimethyl sulfone)  \
0_1                                        0.324772   
0_2                                        0.004501   

Compounds  Dodecan-3-ylbenzene (3-Phenyldodecane)   2-Phenylethanol    \
0_1                                            0.0           0.000000   
0_2                                            0.0           0.005626   

Compounds  2-Phenylacetonitrile  1,4-Butanediol  Benzeneacetonitrile  \
0_1                     0.03144             0.0                  0.0   
0_2                     0.00000             0.0                  0.0   

Compounds  Nonadecane  
0_1               0.0  
0_2               0.0  

[2 rows x 191 columns]

In [2]:
data = pd.read_excel('./data/GC_Volatile_data.xlsx', index_col=0)
data.head(2)

Carbon disulfide  Methylsulfanylmethane (Dimethyl sulfide)  \
A0-1          0.130670                                       0.0   
A0-2          0.167196                                       0.0   

      2-Methylheptane  Furan  Propan-2-one  4-Methyloctane  (E)-oct-2-ene  \
A0-1         0.000000    0.0      1.435842        0.517948            0.0   
A0-2         0.027512    0.0      0.952583        0.000000            0.0   

      2-Methylfuran  Butan-2-one  Nonane  ...  \
A0-1            0.0     0.175037     0.0  ...   
A0-2            0.0     0.332735     0.0  ...   

      Undecan-4-ylbenzene (4-Phenylundecane)  Phenylmethanol  \
A0-1                                     0.0             0.0   
A0-2                                     0.0             0.0   

      (1-hydroxy-2,4,4-trimethylpentan-3-yl) 2-methylpropanoate  \
A0-1                                                0.0           
A0-2                                                0.0           

      Methylsulfonylmethane (Dimethyl sulfone)  \
A0-1                                  0.324772   
A0-2                                  0.004501   

      Dodecan-3-ylbenzene (3-Phenyldodecane)  2-Phenylethanol  \
A0-1                                     0.0         0.000000   
A0-2                                     0.0         0.005626   

      2-Phenylacetonitrile  1,4-Butanediol  Benzeneacetonitrile  Nonadecane  
A0-1               0.03144             0.0                  0.0         0.0  
A0-2               0.00000             0.0                  0.0         0.0  

[2 rows x 191 columns]

#### 1-1> 데이터 확인

In [5]:
print(raw_data.shape)
print(raw_data.columns)

(270, 191)
Index(['Carbon disulfide', 'Methylsulfanylmethane (Dimethyl sulfide) ',
       '2-Methylheptane', 'Furan', 'Propan-2-one', '4-Methyloctane  ',
       '(E)-oct-2-ene', '2-Methylfuran', 'Butan-2-one  ', 'Nonane',
       ...
       'Undecan-4-ylbenzene (4-Phenylundecane)', 'Phenylmethanol',
       '(1-hydroxy-2,4,4-trimethylpentan-3-yl) 2-methylpropanoate  ',
       'Methylsulfonylmethane (Dimethyl sulfone)',
       'Dodecan-3-ylbenzene (3-Phenyldodecane) ', '2-Phenylethanol  ',
       '2-Phenylacetonitrile', '1,4-Butanediol', 'Benzeneacetonitrile',
       'Nonadecane'],
      dtype='object', name='Compounds', length=191)


In [8]:
# 0 값의 개수와 비율
zcnt = 0
total_cnt = len(raw_data.columns) * len(raw_data.index)
for c in raw_data.columns:
    zcnt += len(raw_data.loc[raw_data[c] == 0])

print(zcnt, np.round(zcnt/total_cnt, 4))

39144 0.759


In [9]:
# null 값의 개수와 비율
nullcnt = raw_data.isna().sum().sum()
print(nullcnt, np.round(nullcnt / total_cnt, 4))

3 0.0001


In [10]:
# 0이 아닌 값의 개수와 비율
nzcnt = 0
for c in raw_data.columns:
    nzcnt += len(raw_data.loc[raw_data[c] != 0])

print(nzcnt, np.round(nzcnt/total_cnt, 4))

12426 0.241


#### 1-2> 데이터 수정 및 분할

* 데이터 인덱스 수정 (0_1 -> A0-1)
* 컬럼 수정
* sheet 분류

In [11]:
raw_data.index = [('A' + str(x) + '-' + str(y)) for x in [0, 1, 3, 5, 7, 9, 11, 14, 18] for y in range(1, 31)]
raw_data.columns = raw_data.columns.str.strip()
raw_data.head(2)

Compounds  Carbon disulfide  Methylsulfanylmethane (Dimethyl sulfide)  \
A0-1               0.130670                                       0.0   
A0-2               0.167196                                       0.0   

Compounds  2-Methylheptane  Furan  Propan-2-one  4-Methyloctane  \
A0-1              0.000000    0.0      1.435842        0.517948   
A0-2              0.027512    0.0      0.952583        0.000000   

Compounds  (E)-oct-2-ene  2-Methylfuran  Butan-2-one  Nonane  ...  \
A0-1                 0.0            0.0     0.175037     0.0  ...   
A0-2                 0.0            0.0     0.332735     0.0  ...   

Compounds  Undecan-4-ylbenzene (4-Phenylundecane)  Phenylmethanol  \
A0-1                                          0.0             0.0   
A0-2                                          0.0             0.0   

Compounds  (1-hydroxy-2,4,4-trimethylpentan-3-yl) 2-methylpropanoate  \
A0-1                                                     0.0           
A0-2                                                     0.0           

Compounds  Methylsulfonylmethane (Dimethyl sulfone)  \
A0-1                                       0.324772   
A0-2                                       0.004501   

Compounds  Dodecan-3-ylbenzene (3-Phenyldodecane)  2-Phenylethanol  \
A0-1                                          0.0         0.000000   
A0-2                                          0.0         0.005626   

Compounds  2-Phenylacetonitrile  1,4-Butanediol  Benzeneacetonitrile  \
A0-1                    0.03144             0.0                  0.0   
A0-2                    0.00000             0.0                  0.0   

Compounds  Nonadecane  
A0-1              0.0  
A0-2              0.0  

[2 rows x 191 columns]

In [ ]:
# raw_data.to_excel('./data/GC_Volatile_data.xlsx', sheet_name='RAW_DATA')

In [12]:
raw_sheet2 = pd.read_excel('./data/raw_data/(Metabolite)GC-Volatile_250529.xlsx', sheet_name='RAW_DATA (화합물분류)')
raw_sheet2 = raw_sheet2.drop(columns=raw_sheet2.columns[2:], axis=1)
raw_sheet2.head(2)

Compounds class                                  Compounds
0  S containing compounds                           Carbon disulfide
1  S containing compounds  Methylsulfanylmethane (Dimethyl sulfide)

In [13]:
raw_sheet2 = raw_sheet2[['Compounds', 'Compounds class']]
raw_sheet2.columns = ['Compounds', 'Class']
raw_sheet2['Compounds'] = raw_sheet2['Compounds'].str.strip()
raw_sheet2.head(2)

Compounds                   Class
0                          Carbon disulfide  S containing compounds
1  Methylsulfanylmethane (Dimethyl sulfide)  S containing compounds

In [ ]:
# raw_sheet2.to_excel('./data/GC_Volatile_class.xlsx', sheet_name='RAW_DATA (class)',index=0)

#### 1-3> 일자별 분할

In [3]:
data['days'] = data.index.str.split('A').str[1]
data['days'] = data['days'].str.split('-').str[0].astype(int)
data['days']

A0-1       0
A0-2       0
A0-3       0
A0-4       0
A0-5       0
          ..
A18-26    18
A18-27    18
A18-28    18
A18-29    18
A18-30    18
Name: days, Length: 270, dtype: int64

In [15]:
data['days'].unique()

array([ 0,  1,  3,  5,  7,  9, 11, 14, 18])

In [17]:
for i in data['days'].unique():
    data_day = data.loc[data['days'] == i]
    data_day = data_day.drop(columns='days', axis=1)
    path = './data/GC_Volatile_day' + f"{i:02d}" + '.xlsx'
    data_day.to_excel(path, sheet_name=f"day{i:02d}", index=0)

In [20]:
vol00 = pd.read_excel('./data/GC_Volatile_day00.xlsx')
vol01 = pd.read_excel('./data/GC_Volatile_day01.xlsx')
vol03 = pd.read_excel('./data/GC_Volatile_day03.xlsx')

vol05 = pd.read_excel('./data/GC_Volatile_day05.xlsx')
vol07 = pd.read_excel('./data/GC_Volatile_day07.xlsx')
vol09 = pd.read_excel('./data/GC_Volatile_day09.xlsx')

vol11 = pd.read_excel('./data/GC_Volatile_day11.xlsx')
vol14 = pd.read_excel('./data/GC_Volatile_day14.xlsx')
vol18 = pd.read_excel('./data/GC_Volatile_day18.xlsx')

vol18.head(2)

Carbon disulfide  Methylsulfanylmethane (Dimethyl sulfide)  \
0               0.0                                  0.059838   
1               0.0                                  0.242405   

   2-Methylheptane  Furan  Propan-2-one  4-Methyloctane  (E)-oct-2-ene  \
0              0.0      0      0.000000        0.000000            0.0   
1              0.0      0      0.442002        0.905596            0.0   

   2-Methylfuran  Butan-2-one  Nonane  ...  \
0              0     0.446364       0  ...   
1              0     0.525117       0  ...   

   Undecan-4-ylbenzene (4-Phenylundecane)  Phenylmethanol  \
0                                       0               0   
1                                       0               0   

   (1-hydroxy-2,4,4-trimethylpentan-3-yl) 2-methylpropanoate  \
0                                                  0           
1                                                  0           

   Methylsulfonylmethane (Dimethyl sulfone)  \
0                                  0.042213   
1                                  0.034399   

   Dodecan-3-ylbenzene (3-Phenyldodecane)  2-Phenylethanol  \
0                                       0         0.309898   
1                                       0         0.108116   

   2-Phenylacetonitrile  1,4-Butanediol  Benzeneacetonitrile  Nonadecane  
0                     0               0                  0.0           0  
1                     0               0                  0.0           0  

[2 rows x 191 columns]

In [26]:
from scipy.stats import f_oneway
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

In [27]:
anova1 = data[['3-Methylbutan-1-ol', 'days']]
anova1.columns = ['Methyl', 'days']
anova1.head(2)

Methyl  days
A0-1     0.0     0
A0-2     0.0     0

In [ ]:
grouped = anova1.groupby('days')['Methyl'].apply(list)
grouped

days
0     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
1     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
3     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.060348146, 0....
5     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7     [0.0, 0.0, 0.0, 0.0, 0.0, 0.018619532, 0.0, 0....
9     [0.134831896, 0.143631984, 0.007450522, 0.0113...
11    [5.980286176, 16.1260892, 0.616330194, 5.96112...
14    [6.946721674, 6.542003421, 2.779050382, 1.8441...
18    [6.090099166, 5.796483916, 3.570555808, 4.5594...
Name: 3-Methylbutan-1-ol, dtype: object

In [34]:
f_stat, p_value = f_oneway(*grouped)
print("f_stat: ", f_stat)
print("p_value: ", p_value)

f_stat:  62.952772136061434
p_value:  1.3531844442140145e-56


In [38]:
model = ols("Methyl ~ C(days)", data=anova1).fit()
anova_table = anova_lm(model)

print(anova_table)

             df       sum_sq     mean_sq          F        PR(>F)
C(days)     8.0  1935.106392  241.888299  62.952772  1.353184e-56
Residual  261.0  1002.860460    3.842377        NaN           NaN


#### 사후 검정

ANOVA 검정은 3개 이상의 집단이 동일한지를 비교분석하는 통계 방법  
하지만 검정을 통해 집단 간 차이의 유무만 확인 가능할 뿐, 어떤 집단간 차이가 있는지는 알 수 없다.  
P-value > 0.5 : A = B = C  
P-value < 0.5 : A!=B or B!=C or C!=A or A!=B!=C  

* 사후 분석을 통해 각 집단별로 어떤 차이가 있는지 확인 가능  

tukey : 비교 대상 표본 수가 동일한 경우 가장 많이 사용되는 사후검정 기법  

* 대사체와 날짜간 사후 검정을 통해 일별로 대사체가 차이가 있는지 확인 가능

In [ ]:
from statsmodels.sandbox.stats.multicomp import MultiComparison

In [80]:
comp = MultiComparison(anova1['Methyl'], anova1['days'])
result = comp.tukeyhsd()
tukey_df = pd.DataFrame(data=result._results_table.data[1:], columns=result._results_table.data[0])
tukey_df.loc[tukey_df['reject'] == True]

group1  group2  meandiff   p-adj   lower   upper  reject
5        0      11    7.0538  0.0000  5.4706  8.6369    True
6        0      14    4.7921  0.0000  3.2089  6.3753    True
7        0      18    4.7733  0.0000  3.1901  6.3564    True
12       1      11    7.0538  0.0000  5.4706  8.6369    True
13       1      14    4.7921  0.0000  3.2089  6.3753    True
14       1      18    4.7733  0.0000  3.1901  6.3564    True
18       3      11    7.0421  0.0000  5.4589  8.6253    True
19       3      14    4.7804  0.0000  3.1973  6.3636    True
20       3      18    4.7616  0.0000  3.1784  6.3447    True
23       5      11    7.0538  0.0000  5.4706  8.6369    True
24       5      14    4.7921  0.0000  3.2089  6.3753    True
25       5      18    4.7733  0.0000  3.1901  6.3564    True
27       7      11    7.0507  0.0000  5.4675  8.6338    True
28       7      14    4.7890  0.0000  3.2059  6.3722    True
29       7      18    4.7702  0.0000  3.1870  6.3533    True
30       9      11    6.9829  0.0000  5.3997  8.5661    True
31       9      14    4.7212  0.0000  3.1381  6.3044    True
32       9      18    4.7024  0.0000  3.1192  6.2855    True
33      11      14   -2.2616  0.0004 -3.8448 -0.6785    True
34      11      18   -2.2805  0.0003 -3.8637 -0.6973    True

In [90]:
s = ''
for idx, row in tukey_df.loc[tukey_df['reject'] == True].iterrows():
    s += (str(row['group1']) + '-' + str(row['group2']) + ".")

s = s.split('.')
for i in range(len(s)):
    print(s[i], end='\t')
    if i > 0 and i % 5 == 0:
        print()

0-11	0-14	0-18	1-11	1-14	1-18	
3-11	3-14	3-18	5-11	5-14	
5-18	7-11	7-14	7-18	9-11	
9-14	9-18	11-14	11-18		


In [ ]:
0-3     0-9     0-11    0-14    0-18
1-3     1-9     1-11    1-14    1-18
3-5     3-9     3-11    3-14    3-18
5-9     5-11    5-14    5-18
7-9     7-11    7-14    7-18
9-11    9-14    9-18

### 3> 

In [ ]:
df2_mean_std = []
days = df2['days'].unique()
for day in df2['day'].unique():
    tempdf = pd.DataFrame()
    for col in df2.columns:
        if col == 'day':
            continue
        ser = df2.loc[df2['day'] == day, col]
        ddf = pd.DataFrame({'mean': [ser.mean()], 'std': [ser.std()]}, index=[col])
        tempdf = pd.concat([tempdf, ddf])

    df2_mean_std.append(tempdf)

display(df2_mean_std[0])
display(df2_mean_std[8])

In [ ]:
def VM_meanstd(target, df=df2_mean_std, days=days, draw_errorbar=True):
    vm_df = pd.DataFrame()
    for i in range(len(df)):
        tdf = df[i].loc[[target]]
        tdf.index = days[i:i+1]
        vm_df = pd.concat([vm_df, tdf.iloc[0:1, :]])
    
    if draw_errorbar:
        plt.errorbar(
            vm_df.index, vm_df['mean'], yerr=vm_df['std'],
            fmt='o', linestyle='-',
            color='dodgerblue', ecolor='gray'
        )
        plt.title("Changes of " + target + "(Mean, Std)")
        plt.xlabel('days')
        plt.ylabel('Mean')
        plt.xticks(days)
        # plt.yticks(np.arange(-0.05, 0.26, 0.05))
        plt.grid(axis='y')
        plt.show()

    return vm_df

In [ ]:
three_hydroxybutan_2_one_Acetoin_df = VM_meanstd('3-hydroxybutan-2-one (Acetoin)')

In [ ]:
def eda_single_numeric(var, df, describe=True):
    if describe:
        display(df[var].describe().to_frame().T)
    
    plt.subplot(2,1,1)
    sns.histplot(df[var])
    
    plt.subplot(2,1,2)
    sns.boxplot(x=var, data=df)
    plt.grid()
    plt.tight_layout()
    plt.show()

### PLS-DA

#### 0이 90% 이상인 컬럼 제외한 데이터

In [4]:
data_pls1 = data.copy() # 0이 90% 이상인 컬럼 제거
data_pls1 = data_pls1.replace(0, np.nan)
drop_cols = []
for c in data_pls1.columns:
    x = data_pls1[c].isna().sum()
    zratio = x / data.shape[0] # 0 개수 / 270
    
    if zratio >= 0.9:
        drop_cols.append(c)

print(len(drop_cols))
print(drop_cols[:5])

106
['(E)-oct-2-ene', '2-Methylfuran', 'Nonane', '2,5-Dimethylfuran', 'Cyclopentanol']


In [5]:
data_pls1 = data_pls1.drop(columns=drop_cols, axis=1)
data_pls1 = data_pls1.replace(np.nan, 0)
data_pls1.shape

(270, 86)

In [6]:
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.cross_decomposition import PLSRegression

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [7]:
def my_preprocessing(temp_data, target, random_state_=42):
    X = temp_data.drop(columns=target, axis=1)
    X = X.replace(np.nan, 0)
    Y = temp_data.loc[:, target].astype(int)
    Y = pd.get_dummies(Y, dtype=int)

    x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=random_state_, stratify=Y)

    scaler = StandardScaler()
    x_train = scaler.fit_transform(x_train)
    x_test = scaler.transform(x_test)

    y_test_argmax = y_test.values.argmax(axis=1)

    return x_train, x_test, y_train, y_test_argmax, X, Y

In [8]:
def my_PLS_DA(X_train, X_test, Y_train, Y_test, n_components_=2):
    pls = PLSRegression(n_components=n_components_)
    pls.fit(X_train, Y_train)

    y_pred = pls.predict(X_test)
    y_pred_flatten = [x.argmax() for x in y_pred]

    return pls, y_pred_flatten, Y_test

In [10]:
def plsda_result(y_test, y_pred):
    print("Accuracy :", np.round(accuracy_score(y_test, y_pred), 4))
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))

In [ ]:
# PLS 모델로부터 VIP 점수를 계산하는 함수 정의
def calculate_vip(pls_model):
    T = pls_model.x_scores_      # X score 행렬 (샘플별 컴포넌트), 샘플 수 x 컴포넌트 수
    W = pls_model.x_weights_     # X weight 행렬 (X의 feature가 컴포넌트를 만드는데 기여한 정도) 특성 수 x 컴포넌트 수
    Q = pls_model.y_loadings_    # Y 로딩 행렬 (컴포넌트가 Y를 설명하는데 얼마나 기여하는가) Y 변수 수 x 컴포넌트 수

    p, h = W.shape                # p: X feature 수, h: 컴포넌트 수

    # 컴포넌트별 설명된 분산(SS)을 계산
    SS = np.sum((T ** 2) @ (Q.T ** 2), axis=0)

    vip_scores = np.zeros(p)     # VIP 점수 저장 배열 초기화
    for i in range(p):           # 각 특성에 대해 반복
        weight = np.array([(W[i, j] ** 2) / np.sum(W[:, j] ** 2) for j in range(h)])  # 특성별 중요도 비율 계산
        vip_scores[i] = np.sqrt(p * np.sum(SS * weight) / np.sum(SS))                 # VIP 점수 계산
        
    return vip_scores

In [18]:
T = pls_model1.x_scores_      # X score 행렬 (샘플별 컴포넌트), 샘플 수 x 컴포넌트 수
W = pls_model1.x_weights_     # X weight 행렬 (X의 feature가 컴포넌트를 만드는데 기여한 정도) 특성 수 x 컴포넌트 수
Q = pls_model1.y_loadings_    # Y 로딩 행렬 (컴포넌트가 Y를 설명하는데 얼마나 기여하는가) Y 변수 수 x 컴포넌트 수

p, h = W.shape                # p: X feature 수, h: 컴포넌트 수

In [46]:
np.__version__

'2.0.2'

In [31]:
a = np.array([[1, 0],
              [0, 2],
              [1, 1]])
b = np.array([[-1, 1],
              [3, 2]])

np.sum(a @ b, axis=0)

array([7, 8])

In [42]:
vip_scores3 = calculate_vip(pls_model3)
# len(vip_scores3)
vip_df = pd.DataFrame({
    'Feature': x3.columns,
    'VIP Score': vip_scores3
}).sort_values(by='VIP Score', ascending=False)

vip_df.reset_index(drop=True, inplace=True)

# 중요한 피처 선택 (VIP Score >= 0.9)
important_features = vip_df[vip_df['VIP Score'] >= 0.9]['Feature'].tolist()

In [45]:
print(len(vip_df.loc[vip_df['VIP Score'] >= 0.9]))
vip_df.loc[vip_df['VIP Score'] >= 0.9]

51


Feature  VIP Score
0                                    Butane-2,3-dione   3.161464
1                      3-hydroxybutan-2-one (Acetoin)   3.122862
2                                     2-Phenylethanol   2.569213
3                                  Methyl isovalerate   2.515916
4                                     2-Methylbutanal   2.454995
5                                     3-Methylbutanal   2.352535
6             3-Methylsulfanylpropan-1-ol (Methionol)   2.337057
7                                 Benzeneacetaldehyde   2.322268
8                                         Acetic acid   2.305128
9                  Heptane-2,3-dione (Acetyl valeryl)   2.288813
10                                 3-Methylbutan-1-ol   2.284373
11                                Butane-2,3-diol (1)   2.250683
12                            2,6-Dimethylheptan-4-ol   2.234115
13                           Methyl 2-methylbutanoate   2.213622
14                                Mentha-1,4,8-triene   2.176770
15                                      2-Pentylfuran   2.167851
16                                   Isobutyl alcohol   2.122480
17                                          1-Octanol   2.030191
18                            Ethyl 2-methylbutanoate   1.896336
19                              2-Methylbutanoic acid   1.823602
20                                           Dodecane   1.796324
21                2-Ethylhexyl 2-thiophen-2-ylacetate   1.736559
22                                  2-Ethylhexan-1-ol   1.689528
23         2,2,3,3,4,4,5,5-Octafluorooctyl pentanoate   1.621098
24                                              Furan   1.597884
25                                       Propan-2-one   1.552675
26                                         1-Undecene   1.535602
27                                Butane-2,3-diol (2)   1.493663
28                                     4-Methyloctane   1.467954
29                                     4-Methyldecane   1.463019
30                               2,4-Dimethyldodecane   1.454239
31                                            Ethanol   1.415001
32                       2,2,4,6,6-Pentamethylheptane   1.368914
33                                        Tetradecane   1.364905
34                       Methyl-substituted alkanes 2   1.351612
35                                           Pentanal   1.332861
36                                            Nonanal   1.212037
37  3-Methylbutyl 3-methylbutanoate (Isopentyl iso...   1.209062
38                                       2-Undecanone   1.185670
39                                          Tridecane   1.147200
40                                   Methyl hexanoate   1.094015
41                                    Isoamyl acetate   1.064739
42                                          1-Hexanol   1.045480
43                               5,7-Dimethylundecane   1.035949
44                                             Decane   1.020118
45                            (6S)-6-methyloctan-1-ol   1.010084
46                                    2-Methylheptane   0.988800
47  3,7-dimethylocta-1,6-dien-3-yl 2-methylpropano...   0.961831
48                               4,6-dimethyldodecane   0.946594
49                              2-Furancarboxaldehyde   0.942745
50                               2-Ethylbutanoic acid   0.906019

In [32]:
# pls_model, y_pred, y_test_am = my_PLS_DA(*my_preprocessing(tdata2, 'days'))
x_train, x_test, y_train, y_test, x1, y1, = my_preprocessing(data_pls1, 'days')
pls_model1, y_pred, y_test_am = my_PLS_DA(x_train, x_test, y_train, y_test)

In [33]:
plsda_result(y_test_am, y_pred)

Accuracy : 0.3889
[[0 5 0 0 1 0 0 0 0]
 [0 6 0 0 0 0 0 0 0]
 [0 2 0 0 4 0 0 0 0]
 [0 3 0 0 1 0 0 2 0]
 [0 3 0 0 3 0 0 0 0]
 [0 1 0 0 4 0 0 1 0]
 [0 0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 0 6 0]
 [0 0 0 0 0 0 0 6 0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         6
           1       0.30      1.00      0.46         6
           2       0.00      0.00      0.00         6
           3       0.00      0.00      0.00         6
           4       0.23      0.50      0.32         6
           5       0.00      0.00      0.00         6
           6       1.00      1.00      1.00         6
           7       0.40      1.00      0.57         6
           8       0.00      0.00      0.00         6

    accuracy                           0.39        54
   macro avg       0.21      0.39      0.26        54
weighted avg       0.21      0.39      0.26        54



c:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [12]:
cv = StratifiedKFold(n_splits=5, shuffle=True)
scores = cross_val_score(pls_model1, x1, y1.values.argmax(axis=1), cv=cv)
print("평균 CV accuracy:", np.round(np.mean(scores), 4))
print("개별 CV accuracy:", np.round(scores, 4))

평균 CV accuracy: 0.69
개별 CV accuracy: [0.7254 0.7019 0.5792 0.7267 0.7166]


In [16]:
pls_model1.x_weights_.shape

(85, 2)

#### 전체 데이터 (191 features)

In [127]:
data_pls2 = data.copy()

In [128]:
x_train, x_test, y_train, y_test, x2, y2, = my_preprocessing(data_pls2, 'days')
pls_model2, y_pred, y_test_am = my_PLS_DA(x_train, x_test, y_train, y_test)

In [129]:
plsda_result(y_test_am, y_pred)

Accuracy : 0.3704
[[2 0 4 0 0 0 0 0 0]
 [2 0 4 0 0 0 0 0 0]
 [1 0 1 0 1 2 1 0 0]
 [1 0 3 0 0 0 0 2 0]
 [3 0 0 0 1 2 0 0 0]
 [1 0 1 0 0 4 0 0 0]
 [0 0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 0 6 0]
 [0 0 0 0 0 0 0 6 0]]
              precision    recall  f1-score   support

           0       0.20      0.33      0.25         6
           1       0.00      0.00      0.00         6
           2       0.08      0.17      0.11         6
           3       0.00      0.00      0.00         6
           4       0.50      0.17      0.25         6
           5       0.50      0.67      0.57         6
           6       0.86      1.00      0.92         6
           7       0.43      1.00      0.60         6
           8       0.00      0.00      0.00         6

    accuracy                           0.37        54
   macro avg       0.28      0.37      0.30        54
weighted avg       0.28      0.37      0.30        54



c:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [130]:
cv = StratifiedKFold(n_splits=5, shuffle=True)
scores = cross_val_score(pls_model2, x2, y2.values.argmax(axis=1), cv=cv)
print("평균 CV accuracy:", np.round(np.mean(scores), 4))
print("개별 CV accuracy:", np.round(scores, 4))

평균 CV accuracy: 0.6726
개별 CV accuracy: [0.7897 0.7358 0.4325 0.6589 0.746 ]


#### 0-9일차 vs 11-18일차

In [35]:
data_pls3 = data.copy()
data_pls3['new_group1'] = np.where(data_pls3['days'] < 10, 0, 1)
data_pls3 = data_pls3.drop(columns=['days'], axis=1)
data_pls3['new_group1'].value_counts()

new_group1
0    180
1     90
Name: count, dtype: int64

In [36]:
x_train, x_test, y_train, y_test, x3, y3 = my_preprocessing(data_pls3, 'new_group1')
pls_model3, y_pred, y_test_am = my_PLS_DA(x_train, x_test, y_train, y_test)

plsda_result(y_test_am, y_pred)

Accuracy : 1.0
[[36  0]
 [ 0 18]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       1.00      1.00      1.00        18

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



In [37]:
cv = StratifiedKFold(n_splits=5, shuffle=True)
scores = cross_val_score(pls_model3, x3, y3.values.argmax(axis=1), cv=cv)
print("평균 CV accuracy:", np.round(np.mean(scores), 4))
print("개별 CV accuracy:", np.round(scores, 4))

평균 CV accuracy: 0.7824
개별 CV accuracy: [0.7823 0.834  0.6292 0.8576 0.8089]


#### 0-5일차 vs 7-9일차 vs 11-18일차

In [141]:
data_pls4 = data.copy()
data_pls4.loc[data_pls4['days'] < 6, 'new_group2'] = 0
data_pls4.loc[(data_pls4['days'] > 6) & (data_pls4['days'] < 10), 'new_group2'] = 1
data_pls4.loc[data_pls4['days'] > 10, 'new_group2'] = 2
data_pls4 = data_pls4.drop(columns=['days'], axis=1)
data_pls4['new_group2'] = data_pls4['new_group2'].astype(int)
data_pls4['new_group2'].value_counts().sort_index()

new_group2
0    120
1     60
2     90
Name: count, dtype: int64

In [142]:
x_train, x_test, y_train, y_test, x4, y4 = my_preprocessing(data_pls4, 'new_group2')
pls_model4, y_pred, y_test_am = my_PLS_DA(x_train, x_test, y_train, y_test)

plsda_result(y_test_am, y_pred)

Accuracy : 0.963
[[22  2  0]
 [ 0 12  0]
 [ 0  0 18]]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96        24
           1       0.86      1.00      0.92        12
           2       1.00      1.00      1.00        18

    accuracy                           0.96        54
   macro avg       0.95      0.97      0.96        54
weighted avg       0.97      0.96      0.96        54



In [143]:
cv = StratifiedKFold(n_splits=5, shuffle=True)
scores = cross_val_score(pls_model4, x4, y4.values.argmax(axis=1), cv=cv)
print("평균 CV accuracy:", np.round(np.mean(scores), 4))
print("개별 CV accuracy:", np.round(scores, 4))

평균 CV accuracy: 0.723
개별 CV accuracy: [0.7319 0.758  0.8341 0.7402 0.551 ]
